### ISSUE TITLE
While using Zbar library in a scanning app the Scanning Area Freezes on locking the device.

### ISSUE THREAD

**Issue by varunthakur** [dm77/ZBarScanner#8] opened 2013-04-18 18:49 UTC
i have integrated the zbar library for scanning in my app........when ever i open my scanning activity and lock the device(only in case of honeycomb, 4.0.0 and higher android devices/tabs....works fine for the gingerbread)......and unlock the device the area of the scanning freezes though we can even scan the barcode if it freezes but i have to go back and again launch the scanning activity in order to create the surface again.........

Please Help me with this because i have the sample application of zbar....it behave the same way....is there any issue with the library......what is the appropriate fix for this ???????????.

**Comment by dm77** [comment] 2013-04-19 07:16
@varunthakur - Thanks for reporting the issue and sorry for not replying sooner. Due to my tight work schedule this week, I won't be able to look at this issue until this weekend. Thanks for your patience.

**Comment by varunthakur** [comment] 2013-04-19 07:43
It has now become a show stopper and this issue has been bugging me since a month..........thanks for the support and please suggest me anything u get in the following...Thanks!!!

**Comment by dm77** [comment] 2013-05-01 05:15
Hi @varunthakur. I am looking at your issue as we speak. Please expect a fix in a few hours. Sorry to make you wait.

**Comment by varunthakur** [comment] 2013-05-01 05:31
thats so humble.......but were u able to reproduce the same issue i explained at your end ???

**Comment by varunthakur** [comment] 2013-05-01 05:33
exactly.......it occuring only in 4.x devices only.....whereas it works fine for the gingerbread..

**Comment by dm77** [comment] 2013-05-01 05:34
Yes the issue I saw can be reproduced by these steps:
1.) Open the scanner
2.) Put the device in sleep
3.) Unlock the device
4.) The scanner image is frozen and the only way to recover is go back and
reopen the scanner.

**Comment by varunthakur** [comment] 2013-05-01 05:35
yeaah.........likewise......

**Comment by dm77** [comment] 2013-05-01 07:46
@varunthakur The attached commit should resolve your problem. I tested this on my 4.2 device and couldn't reproduce the problem anymore. Would you mind testing this and letting me know if it resolved your problem? Thank you.

**Comment by varunthakur** [comment] 2013-05-01 11:07
yeah sure....will let you know......

**Comment by varunthakur** [comment] 2013-05-01 11:19
@DushyanthMaguluru   : 

I am using a basic camera preview class in which i pass all the arguments from my activity in CameraPreview constructor..........

/*\* A basic Camera preview class */
public class CameraPreview extends SurfaceView implements SurfaceHolder.Callback {
    private SurfaceHolder mHolder;
    private Camera mCamera;
    private PreviewCallback previewCallback;
    private AutoFocusCallback autoFocusCallback;
    private Context mContext;

```
public CameraPreview(Context context, Camera camera,
                     PreviewCallback previewCb,
                     AutoFocusCallback autoFocusCb) {
    super(context);
    mContext = context;
    mCamera = camera;
    previewCallback = previewCb;
    autoFocusCallback = autoFocusCb;

    /* 
     * Set camera to continuous focus if supported, otherwise use
     * software auto-focus. Only works for API level >=9.
     */
    /*
    Camera.Parameters parameters = camera.getParameters();
    for (String f : parameters.getSupportedFocusModes()) {
        if (f == Parameters.FOCUS_MODE_CONTINUOUS_PICTURE) {
            mCamera.setFocusMode(Parameters.FOCUS_MODE_CONTINUOUS_PICTURE);
            autoFocusCallback = null;
            break;
        }
    }
    */

    // Install a SurfaceHolder.Callback so we get notified when the
    // underlying surface is created and destroyed.
    mHolder = getHolder();
    mHolder.addCallback(this);

    // deprecated setting, but required on Android versions prior to 3.0
    mHolder.setType(SurfaceHolder.SURFACE_TYPE_PUSH_BUFFERS);
}

public void surfaceCreated(SurfaceHolder holder) {
    // The Surface has been created, now tell the camera where to draw the preview.
    try {
        if (mCamera != null) {
            mCamera.setPreviewDisplay(holder);
        } else {
            ToastHelper.showToastMessage(R.string.camera_not_init_msg,
                    mContext, true);
            return;
    }

    } catch (IOException e) {
        LogConfig.logd("CameraPreview", "surfaceCreated()", e);
    }
}

public void surfaceDestroyed(SurfaceHolder holder) {
}

public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
    /*
     * If your preview can change or rotate, take care of those events here.
     * Make sure to stop the preview before resizing or reformatting it.
     */
    if (mHolder.getSurface() == null){
      // preview surface does not exist
      return;
    }

    // stop preview before making changes
    try {
        mCamera.stopPreview();
    } catch (Exception e){
        LogConfig.logd("CameraPreview", "surfaceChanged stop preview", e);
      // ignore: tried to stop a non-existent preview
    }

    try {
        // Hard code camera surface rotation 90 degs to match Activity view in portrait
        mCamera.setDisplayOrientation(90);

        mCamera.setPreviewDisplay(mHolder);
        mCamera.setPreviewCallback(previewCallback);
        mCamera.startPreview();
        mCamera.autoFocus(autoFocusCallback);
    } catch (Exception e){
        LogConfig.logd("CameraPreview", "surfaceChanged rotation", e);
    }
}
```

}

**Comment by dm77** [comment] 2013-05-03 21:04
Hi @varunthakur, Is your problem resolved with the above fix? Let me know.

**Closed as completed** 2013-05-04 20:07 UTC

**Comment by varunthakur** [comment] 2013-05-09 04:46
@DushyanthMaguluru The Problem wasnt solved.......

**Comment by dm77** [comment] 2013-05-09 04:59
@varunthakur If you are using your own CameraPreview class like you mentioned above, I won't be able to fix the problem for you. However if you are seeing the problem specifically with my latest commit, please provide a testcase (what device, OS version, etc.) with a sample application that replicates your issue. Thanks.

**Comment by thedarkside** [comment] 2013-12-30 03:51
@varunthakur I had the same problem some hours ago. I asume, that your `onPause()` method stops the preview. Therefore your `onResume()` method should contain this:

``` java
previewSurface.setVisibility(View.INVISIBLE);
previewSurface.setVisibility(View.VISIBLE);
```

This forces the execution of `surfaceChanged()` which starts your preview again.

I dont know if thats the best solution but it solved my Problem. Hope it helps.

**Comment by sharmilee** [comment] 2014-03-27 06:47
Hi DM,
Can you please suggest me a way to open this app in portrait mode?
because for existing code of your sample, preview size becomes small in case of portrait mode. Please reply soon.
